# Generated by Django 2.1.7 on 2019-04-04 18:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apply_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('email', models.EmailField(max_length=75, unique=True, verbose_name='email address')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='request date')),
            ],
        ),
    ]
